CREATE TABLE IF NOT EXISTS `driftzone_electrician_players` (
    `uid` BIGINT UNSIGNED NOT NULL,
    `employed` TINYINT(1) NOT NULL DEFAULT 0,
    `xp` INT UNSIGNED NOT NULL DEFAULT 0,
    `total_jobs` INT UNSIGNED NOT NULL DEFAULT 0,
    `total_earned` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `shifts_completed` INT UNSIGNED NOT NULL DEFAULT 0,
    `clean_shifts` INT UNSIGNED NOT NULL DEFAULT 0,
    `pending_pay` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
