ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `mute` DATETIME NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `mute_reason` VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `mute_by` INT(11) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `mute_by_name` VARCHAR(64) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `mute_at` DATETIME NULL DEFAULT NULL;

ALTER TABLE `users`
  MODIFY COLUMN `mute` DATETIME NULL DEFAULT NULL;
