'use strict';
const $ = (id) => document.getElementById(id);
const panels = ['adminHelpPanel','adminPanel','coordsPanel','addVehPanel','configVehPanel','ownedVehPanel'].map($);
let currentCoords = '';
let configVehicles = [];
let ownedVehicles = [];
let ownedUid = 0;
let modalCallback = null;
let lastPanelPayload = null;
let activeCategory = 'system';
const SUBS = { DRIFT:['starter','drifter','jdm_legends'], HS:['starter','racer','legend'], PREMIUM:['drift','hs'], CUSTOM:['all'] };
function nui(name, data = {}) { return fetch(`https://${GetParentResourceName()}/${name}`, { method:'POST', headers:{'Content-Type':'application/json; charset=UTF-8'}, body:JSON.stringify(data)}).catch(()=>{}); }
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function num(v){return Number(v||0).toLocaleString('ro-RO');}
function bool(v){return Number(v||0)===1 || v===true;}
function showShell(){ $('shell').classList.remove('hidden'); }
function hideShell(){ $('shell').classList.add('hidden'); }
function closePanels(){ panels.forEach(p=>p&&p.classList.add('hidden')); }
function showPanel(id){ showShell(); closePanels(); $(id).classList.remove('hidden'); }
function closeAll(){ hideModal(); closePanels(); hideShell(); nui('closePanel'); }
function money(row){ return Number(row.dzcoins_price||0)>0 ? `${num(row.dzcoins_price)} DZC` : `$${num(row.price||0)}`; }
function showModal(title, message, options = {}) { const modal=$('confirmModal'); $('confirmTitle').textContent=title||'Confirmare'; $('confirmMessage').textContent=message||'Esti sigur?'; const input=$('confirmInput'); input.value=''; input.placeholder=options.placeholder||''; input.classList.toggle('hidden', options.input!==true); $('confirmOk').textContent=options.okText||'CONFIRMA'; modalCallback=typeof options.onConfirm==='function'?options.onConfirm:null; modal.classList.remove('hidden'); setTimeout(()=>{ if(options.input===true) input.focus(); else $('confirmOk').focus(); }, 50); }
function hideModal(){ $('confirmModal').classList.add('hidden'); modalCallback=null; }
function confirmModalOk(){ const value=($('confirmInput').value||'').trim(); const fn=modalCallback; hideModal(); if(fn) fn(value); }
function confirmModalCancel(){ hideModal(); }
async function copyText(text){ try{ await navigator.clipboard.writeText(text); $('status').textContent='Coordonatele au fost copiate.'; }catch(e){ $('coordsInput').select(); document.execCommand('copy'); } }
function showCoords(data={}){ currentCoords=String(data.coords||''); $('coordsInput').value=currentCoords; $('xInput').value=Number(data.x||0).toFixed(6); $('yInput').value=Number(data.y||0).toFixed(6); $('zInput').value=Number(data.z||0).toFixed(6); $('headingInput').value=Number(data.heading||0).toFixed(2); $('dimensionInput').value=Number(data.dimension||0); showPanel('coordsPanel'); setTimeout(()=>copyText(currentCoords),100); }
function copyCoords(){ copyText(currentCoords); }
function syncSubcategories(value){ const sec=value||$('carSectionInput').value||'DRIFT'; const sel=$('carSubcategoryInput'); sel.innerHTML=(SUBS[sec]||['all']).map(s=>`<option value="${s}">${s}</option>`).join(''); }
function showAddVeh(){ showPanel('addVehPanel'); $('addCarStatus').textContent='Completeaza campurile.'; $('addCarStatus').className='status'; ['Model','Name','Image'].forEach(k=>{const e=$(`car${k}Input`); if(e)e.value='';}); $('carPriceInput').value='0'; $('carDzcoinsInput').value='0'; $('carCategoryInput').value='1'; $('carSectionInput').value='DRIFT'; syncSubcategories('DRIFT'); $('carVipInput').value='0'; $('carApearInput').value='1'; $('carSellingInput').value='1'; $('carTradebleInput').value='1'; $('carTunableInput').value='1'; $('carTypeInput').value='drift'; $('imagePreviewBox').classList.add('hidden'); setTimeout(()=>$('carModelInput').focus(),60); }
function previewCarImage(){ const url=String($('carImageInput').value||'').trim(); if(!url){$('imagePreviewBox').classList.add('hidden');return;} $('carImagePreview').src=url; $('imagePreviewBox').classList.remove('hidden'); }
function vehPayload(prefix='car'){ return {model:$(`${prefix}ModelInput`).value.trim(),name:$(`${prefix}NameInput`).value.trim(),price:Number($(`${prefix}PriceInput`).value||0),dzcoins_price:Number($(`${prefix}DzcoinsInput`).value||0),category:Number($(`${prefix}CategoryInput`).value||1),showroom_section:$(`${prefix}SectionInput`).value,showroom_subcategory:$(`${prefix}SubcategoryInput`).value,vip:Number($(`${prefix}VipInput`).value||0),apear:Number($(`${prefix}ApearInput`).value||1),selling:Number($(`${prefix}SellingInput`).value||1),tradeble:Number($(`${prefix}TradebleInput`).value||1),tunable:Number($(`${prefix}TunableInput`).value||1),type:$(`${prefix}TypeInput`).value,image:$(`${prefix}ImageInput`).value.trim()}; }
function submitAddCar(){ const p=vehPayload('car'); if(!p.model||!p.name){$('addCarStatus').textContent='Model si nume obligatorii.';$('addCarStatus').className='status error';return;} $('addCarStatus').textContent='Se salveaza...'; nui('submitAddCar',p); }
function addVehResult(data){ $('addCarStatus').textContent=data.message||'Result'; $('addCarStatus').className='status '+(data.ok?'success':'error'); }
function showConfigVeh(data={}){ configVehicles=Array.isArray(data.vehicles)?data.vehicles:[]; showPanel('configVehPanel'); renderConfigVeh(); }
function renderConfigVeh(){ const q=String($('configSearch').value||'').toLowerCase().trim(); const list=configVehicles.filter(v=>!q||`${v.id} ${v.vehicle_model||v.model} ${v.vehicle_name||v.name} ${v.showroom_section} ${v.showroom_subcategory}`.toLowerCase().includes(q)); $('configList').innerHTML=list.map(configCard).join('')||'<div class="empty">Nu exista masini.</div>'; setTimeout(hydrateConfigSubs,0); }
function configCard(v){ const id=Number(v.id||0); const model=v.vehicle_model||v.model||''; const name=v.vehicle_name||v.name||''; return `<div class="veh-config-card"><div class="card-head"><b>#${id} ${esc(name)}</b><span>${esc(model)} • ${money(v)}</span></div><div class="grid four compact"><div><label>MODEL</label><input id="cfg${id}ModelInput" value="${esc(model)}"></div><div><label>NAME</label><input id="cfg${id}NameInput" value="${esc(name)}"></div><div><label>CASH</label><input id="cfg${id}PriceInput" type="number" value="${Number(v.price||0)}"></div><div><label>DZC</label><input id="cfg${id}DzcoinsInput" type="number" value="${Number(v.dzcoins_price||0)}"></div></div><div class="grid five compact"><div><label>SECTION</label><select id="cfg${id}SectionInput" onchange="syncConfigSub(${id})">${['DRIFT','HS','PREMIUM','CUSTOM'].map(s=>`<option ${String(v.showroom_section||'').toUpperCase()===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>SUB</label><select id="cfg${id}SubcategoryInput"></select></div><div><label>CAT NR</label><input id="cfg${id}CategoryInput" type="number" value="${Number(v.category||1)}"></div><div><label>TYPE</label><select id="cfg${id}TypeInput">${['drift','hs','premium','custom'].map(s=>`<option value="${s}" ${String(v.type||'')===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>IMAGE</label><input id="cfg${id}ImageInput" value="${esc(v.image||'')}"></div></div><div class="grid five compact">${select01(`cfg${id}VipInput`,'VIP',v.vip)}${select01(`cfg${id}ApearInput`,'APEAR',v.apear)}${select01(`cfg${id}SellingInput`,'SELLING',v.selling)}${select01(`cfg${id}TradebleInput`,'TRADE',v.tradeble ?? v.tradable)}${select01(`cfg${id}TunableInput`,'TUNABLE',v.tunable)}</div><div class="buttons right"><button onclick="saveConfigVeh(${id})">EDIT / SAVE</button><button class="danger" onclick="deleteConfigVeh(${id})">DELETE</button></div></div>`; }
function select01(id,label,val){return `<div><label>${label}</label><select id="${id}"><option value="1" ${bool(val)?'selected':''}>1</option><option value="0" ${!bool(val)?'selected':''}>0</option></select></div>`;}
function syncConfigSub(id){ const sec=$(`cfg${id}SectionInput`).value; const sel=$(`cfg${id}SubcategoryInput`); const old=(configVehicles.find(v=>Number(v.id)===id)||{}).showroom_subcategory; sel.innerHTML=(SUBS[sec]||['all']).map(s=>`<option value="${s}" ${old===s?'selected':''}>${s}</option>`).join(''); }
function hydrateConfigSubs(){ configVehicles.forEach(v=>{const id=Number(v.id||0); if($(`cfg${id}SubcategoryInput`)) syncConfigSub(id);}); }
function cfgPayload(id){ return {model:$(`cfg${id}ModelInput`).value.trim(),name:$(`cfg${id}NameInput`).value.trim(),price:Number($(`cfg${id}PriceInput`).value||0),dzcoins_price:Number($(`cfg${id}DzcoinsInput`).value||0),category:Number($(`cfg${id}CategoryInput`).value||1),showroom_section:$(`cfg${id}SectionInput`).value,showroom_subcategory:$(`cfg${id}SubcategoryInput`).value,vip:Number($(`cfg${id}VipInput`).value||0),apear:Number($(`cfg${id}ApearInput`).value||1),selling:Number($(`cfg${id}SellingInput`).value||1),tradeble:Number($(`cfg${id}TradebleInput`).value||1),tunable:Number($(`cfg${id}TunableInput`).value||1),type:$(`cfg${id}TypeInput`).value,image:$(`cfg${id}ImageInput`).value.trim()}; }
function saveConfigVeh(id){ nui('configVehSave',{id,payload:cfgPayload(id)}); $('configStatus').textContent='Se salveaza...'; }
function deleteConfigVeh(id){ showModal('Delete vehicle config', `Stergi masina #${id}?`, { okText:'DELETE', onConfirm:()=>nui('configVehDelete',{id}) }); }
function showOwnedVehs(data={}){ ownedUid=Number(data.uid||0); ownedVehicles=Array.isArray(data.vehicles)?data.vehicles:[]; $('ownedTitle').textContent=`VEHS UID ${ownedUid}`; $('ownedKicker').textContent=data.name||'Owned Vehicles'; showPanel('ownedVehPanel'); renderOwnedVehs(); }
function renderOwnedVehs(){ const q=String($('ownedSearch').value||'').toLowerCase().trim(); const list=ownedVehicles.filter(v=>!q||`${v.id} ${v.vehicle_model} ${v.vehicle_plate} ${v.vehicle_name||''}`.toLowerCase().includes(q)); $('ownedList').innerHTML=list.map(ownedCard).join('')||'<div class="empty">Nu exista masini.</div>'; }
function ownedCard(v){ const id=Number(v.id||0); const img=v.image?`<img src="${esc(v.image)}">`:'NO IMG'; return `<div class="owned-card"><div class="owned-img">${img}</div><div class="owned-info"><b>#${id} ${esc(v.vehicle_name||v.vehicle_model)}</b><span>Model: ${esc(v.vehicle_model)} • Plate: ${esc(v.vehicle_plate||'-')}</span><span>Owner: ${esc(v.owner_id||ownedUid)} • Gradient: ${esc(v.gradient||0)}</span></div><div class="owned-actions"><button onclick="ownedAction('spawn',${id})">SPAWN</button><button onclick="ownedAction('goto',${id})">GO TO</button><button onclick="ownedTransfer(${id})">TRANSFER</button><button class="danger" onclick="ownedTake(${id})">TAKE</button></div></div>`; }
function ownedAction(action,id,extra={}){ nui('ownedVehAction',{action,uid:ownedUid,vehicleId:id,extra}); }
function ownedTake(id){ showModal('TAKE VEHICLE', `Stergi masina SQL #${id}?`, { okText:'TAKE', onConfirm:()=>ownedAction('take',id) }); }
function ownedTransfer(id){ showModal('TRANSFER VEHICLE', `UID nou pentru masina SQL #${id}:`, { input:true, placeholder:'UID nou', okText:'TRANSFER', onConfirm:(uid)=>ownedAction('transfer',id,{newUid:Number(uid)}) }); }
function panelResult(data){ const msg=data.message||'Result'; ['configStatus','ownedStatus','addCarStatus'].forEach(id=>{ if($(id)) { $(id).textContent=msg; $(id).className='status '+(data.ok?'success':'error'); } }); }
function commandArgsFromSyntax(syntax){ return String(syntax||'').replace(/^\/\w+\s*/,'').trim(); }
function commandCard(c, runnable){ const ph=commandArgsFromSyntax(c.syntax); return `<article class="cmd-card" data-category="${esc(c.category)}"><div><b>/${esc(c.name)}</b><span>Level ${esc(c.level)}${c.needDuty?' • aduty':' • fara aduty'}</span></div><p>${esc(c.description)}</p><code>${esc(c.syntax)}</code>${runnable?`<div class="run-row"><input id="cmdArgs_${esc(c.name)}" placeholder="${esc(ph||'fara argumente')}"><button onclick="runCommand('${esc(c.name)}')">RUN</button></div>`:''}</article>`; }
function runCommand(name){ const input=$(`cmdArgs_${name}`); nui('runAdminCommand',{command:name,args:input?input.value:''}); }
function cats(payload){ const used=new Set((payload.commands||[]).map(c=>c.category)); const all=payload.categories||[]; return all.filter(c=>used.has(c.id)); }
function renderHelp(payload){ lastPanelPayload=payload||{}; const cmds=payload.commands||[]; const byLevel={}; cmds.forEach(c=>{ byLevel[c.level]=byLevel[c.level]||[]; byLevel[c.level].push(c); }); $('adminHelpPanel').innerHTML=`<div class="admin-head"><div><span>DriftZone Admin</span><h1>Admin Help</h1><p>${esc(payload.admin?.rank||'Staff')} • Level ${esc(payload.admin?.level||0)} • ${esc(payload.admin?.username||'')}</p></div><button class="ghost" onclick="closeAll()">ESC</button></div><div class="help-grid">${Object.keys(byLevel).sort((a,b)=>a-b).map(l=>`<section class="help-level"><h3>Level ${l}</h3><div class="cmd-grid">${byLevel[l].map(c=>commandCard(c,false)).join('')}</div></section>`).join('')}</div>`; showPanel('adminHelpPanel'); }
function renderAdminPanel(payload){ lastPanelPayload=payload||{}; const categories=cats(payload); if(!categories.find(c=>c.id===activeCategory)) activeCategory=(categories[0]&&categories[0].id)||'system'; const commands=(payload.commands||[]).filter(c=>c.category===activeCategory); $('adminPanel').innerHTML=`<div class="admin-head"><div><span>DriftZone Admin</span><h1>Admin Panel</h1><p>${esc(payload.admin?.rank||'Staff')} • Level ${esc(payload.admin?.level||0)}</p></div><button class="ghost" onclick="closeAll()">ESC</button></div><div class="ap-layout"><aside class="ap-cats">${categories.map(c=>`<button class="${c.id===activeCategory?'active':''}" onclick="setApCat('${esc(c.id)}')">${esc(c.label)}</button>`).join('')}</aside><section class="ap-content"><div class="cmd-grid">${commands.map(c=>commandCard(c,true)).join('')}</div></section></div>`; showPanel('adminPanel'); }
function setApCat(cat){ activeCategory=cat; renderAdminPanel(lastPanelPayload||{}); }
window.addEventListener('message', (event)=>{ const data=event.data||{}; if(data.action==='coords') showCoords(data.data||{}); if(data.action==='addVeh') showAddVeh(data.data||{}); if(data.action==='addVehResult') addVehResult(data); if(data.action==='configVeh') showConfigVeh(data.data||{}); if(data.action==='ownedVehs') showOwnedVehs(data.data||{}); if(data.action==='panelResult') panelResult(data); if(data.action==='adminHelp') renderHelp(data.data||{}); if(data.action==='adminPanel') renderAdminPanel(data.data||{}); });
document.addEventListener('keydown', e=>{ if(e.key==='Escape') closeAll(); });
syncSubcategories('DRIFT');
