CREATE TABLE IF NOT EXISTS `driftzone_status` (
    `identifier` VARCHAR(80) NOT NULL,
    `food` TINYINT UNSIGNED NOT NULL DEFAULT 100,
    `water` TINYINT UNSIGNED NOT NULL DEFAULT 100,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
