USE `driftzone`;

ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `Rank` VARCHAR(64) NOT NULL DEFAULT 'Newbie';
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `rankcolor` VARCHAR(16) NOT NULL DEFAULT '#04c7f7';
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `xp` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `playtime` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `cash` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `dzcoins` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `admin_level` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `aduty` VARCHAR(8) NOT NULL DEFAULT 'no';

CREATE TABLE IF NOT EXISTS `stats_logs` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `uid` INT NOT NULL DEFAULT 0,
    `username` VARCHAR(64) NOT NULL DEFAULT '',
    `action` VARCHAR(64) NOT NULL DEFAULT '',
    `data` LONGTEXT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `uid_idx` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
