ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `xp` INT NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `rank` VARCHAR(50) NOT NULL DEFAULT 'Newbie';
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `rankcolor` VARCHAR(16) NOT NULL DEFAULT '#ffffff';

CREATE INDEX IF NOT EXISTS `idx_users_xp` ON `users` (`xp`);
