ALTER TABLE users ADD COLUMN IF NOT EXISTS dzcoins INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cash INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS garageslots INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS outsidevehicles INT NOT NULL DEFAULT 0;
